<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Array: php</title>
</head>
<body>
    
    
    <?php
// variable
// $myVariable = "Hello World";
// echo $myVariable;
// echo "<br>";

// echo "This is variable: $myVariable";
// echo "<br>";

// array
$myArray = array("John", "Mary", "Peter", "Sally");
// $myArray2 = ["Bob", 10];
echo "<pre>";
    print_r($myArray);
?>

<h1>Types of array:</h1>

<ol style="list-style-type='i';">
<li>Index/Numeric array: key is numeric and starts from 0 to serially key is generated by the server</li>

<pre>
eg: @fruits = ["apple", "orange", "banana", "mango"];
0         1         2         3
</pre>

<p>Php code:</p>
<?php
    $fruits = ["apple", "orange", "banana", "mango"];
    echo "<pre>";
    print_r($fruits);
    echo "</pre>";
    echo "<br>";
    echo $fruits[0];
    echo "<br>";
    echo $fruits[1];
    echo "<br>";
    echo $fruits[2];
    echo "<br>";
    echo $fruits[3];
?>

<li>Associative array: Key is given by user and can be string or literals.</li>
<pre>
eg: @fruits = ["a" => "apple", "b" => "orange", "c" => "banana", "d" => "mango"];
</pre>
<p>Php code:</p>
<?php
    $fruits = ["a" => "apple", "b" => "orange", "c" => "banana", "d" => "mango"];
    echo "<pre>";
    print_r($fruits);
    echo "</pre>";
    echo "<br>";
    echo $fruits["a"];
    echo "<br>";
    echo $fruits["b"];
    echo "<br>";
    echo $fruits["c"];
    echo "<br>";
    echo $fruits["d"];
?>
</ol>
</body>
</html>